### ISSUE TITLE
FileLogger 只会创建空的日期文件夹，不会创建新的log文件

### ISSUE THREAD

**Issue by kekeslife** [RRQM/TouchSocket#11]
https://github.com/RRQM/TouchSocket/blob/f4e48dfdf87952ab91e214ca82f333c4f60488c8/src/TouchSocket/Core/Logger/FileLogger.cs#L82-L86

**Comment by RRQM** [comment]
新文件会在检验m_writer后创建的。

**Comment by kekeslife** [comment]
使用代码如下：
`config.Container.SetSingletonLogger(new FileLogger("D:\\log\\"));`

产生的log如下，log全部写在[2022-09-09] 0000.log文件里面

![未命名](https://user-images.githubusercontent.com/4279196/190031296-f09622de-952b-4c61-b425-71c6e16c7711.png)
