### ISSUE TITLE
远程终端拒绝该操作

### ISSUE THREAD

**Issue by zmglgylc** [RRQM/TouchSocket#18]
RemoteDirectoryInfoResult rootDirectoryInfoResult =await client.GetDirectoryInfoAsync(@"E:\\backup\\");
E:\\backup为远程服务器(公网IP)上的文件夹，
结果：
fileinfo:null
Message:远程终端拒绝该操作，反馈信息：。
ResultCode:TouchSocket.Core.ResultCode.Error

**Comment by zmglgylc** [comment]
请问怎么解决这个问题呢

**Comment by RRQM** [comment]
看文档
