### ISSUE TITLE
TCP引用断线重连报错

### ISSUE THREAD

**Issue by ArsenalHolmes** [RRQM/TouchSocket#23]
tcpClient = new TcpClient();
            tcpClient.Connected = (client, e) => {
                Console.WriteLine($"{DateTime.Now}：中控服务器、连接成功");
            };//成功连接到服务器

            tcpClient.Disconnected = (client, e) => {
                Console.WriteLine($"{DateTime.Now}：中控服务器、断开连接");
            };//从服务器断开连接，当连接不成功时不会触发。

            tcpClient.Received = (client, byteBlock, requestInfo) =>
            {

            };

            tcpClient.Setup(new TouchSocketConfig().
                SetRemoteIPHost($"{ip}:{port}").
                ConfigurePlugins((a) =>
            {

                a.UseReconnection(-1, false, 1000 * 5, (e) =>
                {
                    Console.WriteLine($"{DateTime.Now}：中控服务器、重新连接成功");
                });

            }));

UseReconnection 这句代码的时候报错。注释掉就没问题了。
![SY](https://github.com/RRQM/TouchSocket/assets/30106226/d920b521-28ad-451a-be2b-d4b7eeee461e)

我是同时开启了TCP和UDP服务器。不知道跟这个有没有关系。突然报开这个错了。之前是可以运行的。没有进行升级操作

**Comment by RRQM** [comment]
netf平台或许有这个bug。请更新最新组件
