### ISSUE TITLE
Unity 环境使用tcpDmtp 服务建立连接失败 Error | 这可能不是Dmtp协议数据

### ISSUE THREAD

**Issue by TomeTao9527** [RRQM/TouchSocket#26]
参照说明文档：导入unity packetage 包
使用untiy example 中的服务端项目本地运行

tcp 及 udp 的连接都正常

但使用tcpDmtp 测试demo时，提示`Error | 这可能不是Dmtp协议数据`

![image](https://github.com/RRQM/TouchSocket/assets/70026540/cefec93e-5f0a-4546-94a5-28fed74780b2)
![image](https://github.com/RRQM/TouchSocket/assets/70026540/d364ac44-24c0-4d15-9594-773ba1291761)

**Comment by TomeTao** [comment]
大佬，我花了点时间，测试发现是unitypackage的问题，怀疑需要重新构造dll文件

**Comment by RRQM** [comment]
ok
