### ISSUE TITLE
测试HttpService 请求是单线程处理的，并发请求后来的会被阻塞住

### ISSUE THREAD

**Issue by wxtkdy** [RRQM/TouchSocket#29]
HttpService ParseHttpServer = new HttpService();
ParseHttpServer.Setup(new TouchSocketConfig()//加载配置
    .SetListenIPHosts(ServerConfig.PraseServerPort)
    .ConfigureContainer(a =>
    {
        a.AddConsoleLogger();
    })
    .ConfigurePlugins(a =>
    {
        a.Add<MyHttpPlug_Get>();
        a.Add<MyHttpPlug_Post>();
        //default插件应该最后添加，其作用是
        //1、为找不到的路由返回404
        //2、处理header为Option的探视跨域请求。
        a.UseDefaultHttpServicePlugin();
    }));
ParseHttpServer.Start();

**Comment by RRQM** [comment]
https://gitee.com/RRQM_Home/TouchSocket/issues/I96X94
