### ISSUE TITLE
Can't start transfer while the file size over 11GB.

### ISSUE THREAD

**Issue by Chaos-s** [RRQM/TouchSocket#3]
The Transfer can't work with huge size files.

**Comment by RRQM** [comment]
Please describe your problem in detail and show some useful code as much as possible so that I can quickly locate the problem.

**Comment by Chaos-s** [comment]
![image](https://user-images.githubusercontent.com/71606749/152980114-b89786bd-1368-4586-b8e2-b8906a07b96f.png)
使用的是Demo里面的内容，发现只要任务文件大于10GB，比如图片里的是一个12G文件，传输无法启动，就停在这里了。

**Comment by Chaos-s** [comment]
> Please describe your problem in detail and show some useful code as much as possible so that I can quickly locate the problem.

RRQM大大你好，如图

**Comment by RRQM** [comment]
理论上应该不会出现这样的问题，但是需要注意的是，文件在传输之前都需要进行验证，设置属性在fileRequest.FileCheckerType，默认情况下是MD5验证，所以，当文件太大时，可能执行时间太长而导致的，你可以多等一会时间，或者设置fileRequest.FileCheckerType = FileCheckerType.None;
