### ISSUE TITLE
收到数据的最大长度为16384，客户端发送数据与服务端接收数据不匹配

### ISSUE THREAD

**Issue by SongSongso** [RRQM/TouchSocket#30]
![image](https://github.com/RRQM/TouchSocket/assets/46993491/be3e7710-eaaf-419b-bef4-336fd6791956)
![image](https://github.com/RRQM/TouchSocket/assets/46993491/7e1a5aa5-7957-4e20-ad77-7629e26a6c44)

**Comment by RRQM** [comment]
https://gitee.com/RRQM_Home/TouchSocket/issues/I979GQ
