### ISSUE TITLE
net framework4.7.2 tcpclient连接以后，online变量还是flase

### ISSUE THREAD

**Issue by Princebin** [RRQM/TouchSocket#4]
net framework4.7.2 tcpclient连接以后，online变量还是flase

**Comment by RRQM** [comment]
那个组件？那个版本？怎么操作的？你从那个时机获取的Online属性？

**Comment by RRQM** [comment]
因为版本差异太大。建议您升级最新版使用，如果升级有困难，那您可以下载：[4.x版本源码](https://github.com/RRQM/RRQMSocket/tree/4.x%E7%89%88%E6%9C%AC)，然后自己调试看看。
