### ISSUE TITLE
串口数据接收延迟

### ISSUE THREAD

**Issue by Princebin** [RRQM/TouchSocket#47]
版本3.0
在avalonia中使用SerialPortClient，出现接收数据严重延时的情况，数据沾包。
串口设置如下
serialPortClient.SetupAsync(new TouchSocketConfig()
				.SetSerialPortOption(new SerialPortOption()
				 {
					 BaudRate = 115200,//波特率
					 DataBits = 8,//数据位
					 Parity = Parity.None,//校验位
					 PortName = SelectedCOM,//COM
					 StopBits = StopBits.One//停止位
				 }
				 .SetSerialDataHandlingAdapter(() => new PeriodPackageAdapter()));
				serialPortClient.ConnectAsync();

**Comment by RRQM** [comment]
感谢您的反馈！

由于你使用了`PeriodPackageAdapter`适配器，导致的接收时间较长。

你可以使用下面设置：

`.SetSerialDataHandlingAdapter(() => new PeriodPackageAdapter() { CacheTimeout = TimeSpan.FromMilliseconds(100) })`
