### ISSUE TITLE
内存池字节块长度分配优化建议

### ISSUE THREAD

**Issue by theta25** [RRQM/TouchSocket#5]
HitSize函数直接根据输入 ***X*** 求解

![](https://latex.codecogs.com/svg.image?a&space;=&space;\log_2&space;X)
![](https://latex.codecogs.com/svg.image?b&space;=&space;2^{\lceil&space;a&space;\rceil})

**Comment by RRQM** [comment]
感谢您的建议，但是计算的方式来执行并不可行。首先switch的效率会比计算的快约1000倍。其次，内存块的设计主旨并不是获得“需求”大小的内存，而是将内存在可使用范围内复用，以达到节约申请内存时间和避免内存碎片化问题。最后，RRQM也考虑到HitSize或许在极端环境中无法高频命中的问题，所以也增加了AddSizeKey的方法，如何您的业务中需要频繁申请大数据，那么您可以添加一个适当值，当下次获取时，将不会执行HitSize，而是直接从池中获取。
